// Mock data for the second-brain app

const BOOKS = [
  {
    id: 'flow',
    title: 'Flow',
    subtitle: 'A Psicologia do Alto Desempenho',
    author: 'Mihaly Csikszentmihalyi',
    year: 1990,
    pages: 412,
    color: '#8b5a3c',
    accent: '#d97757',
    spine: 'warm',
    addedDays: 124,
    chapters: 11,
    highlights: 47,
    tags: ['psicologia', 'produtividade'],
    status: 'processed',
  },
  {
    id: 'meditations',
    title: 'Meditações',
    subtitle: null,
    author: 'Marco Aurélio',
    year: 180,
    pages: 254,
    color: '#3a3a3a',
    accent: '#a8a29e',
    spine: 'dark',
    addedDays: 312,
    chapters: 12,
    highlights: 89,
    tags: ['filosofia', 'estoicismo'],
    status: 'processed',
  },
  {
    id: 'thinking',
    title: 'Rápido e Devagar',
    subtitle: 'Duas formas de pensar',
    author: 'Daniel Kahneman',
    year: 2011,
    pages: 608,
    color: '#1e3a5f',
    accent: '#5b8fb9',
    spine: 'cool',
    addedDays: 89,
    chapters: 38,
    highlights: 134,
    tags: ['psicologia', 'decisão', 'economia'],
    status: 'processed',
  },
  {
    id: 'sapiens',
    title: 'Sapiens',
    subtitle: 'Uma breve história da humanidade',
    author: 'Yuval Noah Harari',
    year: 2011,
    pages: 528,
    color: '#6b4423',
    accent: '#c8a165',
    spine: 'warm',
    addedDays: 201,
    chapters: 20,
    highlights: 76,
    tags: ['história', 'antropologia'],
    status: 'processed',
  },
  {
    id: 'atomic',
    title: 'Hábitos Atômicos',
    subtitle: null,
    author: 'James Clear',
    year: 2018,
    pages: 320,
    color: '#0a4d3e',
    accent: '#7ca982',
    spine: 'cool',
    addedDays: 45,
    chapters: 20,
    highlights: 62,
    tags: ['produtividade', 'hábitos'],
    status: 'processed',
  },
  {
    id: 'antifragile',
    title: 'Antifrágil',
    subtitle: 'Coisas que se beneficiam com o caos',
    author: 'Nassim Taleb',
    year: 2012,
    pages: 544,
    color: '#2b2b2b',
    accent: '#e8b923',
    spine: 'dark',
    addedDays: 178,
    chapters: 25,
    highlights: 103,
    tags: ['filosofia', 'risco', 'economia'],
    status: 'processed',
  },
  {
    id: 'deepwork',
    title: 'Trabalho Focado',
    subtitle: 'Regras para o sucesso num mundo distraído',
    author: 'Cal Newport',
    year: 2016,
    pages: 304,
    color: '#1a1a2e',
    accent: '#9bb5d6',
    spine: 'cool',
    addedDays: 67,
    chapters: 7,
    highlights: 41,
    tags: ['produtividade', 'foco'],
    status: 'processed',
  },
  {
    id: 'tao',
    title: 'Tao Te Ching',
    subtitle: null,
    author: 'Lao Tsé',
    year: -400,
    pages: 142,
    color: '#5c2a1e',
    accent: '#d4a574',
    spine: 'warm',
    addedDays: 256,
    chapters: 81,
    highlights: 28,
    tags: ['filosofia', 'taoísmo'],
    status: 'processed',
  },
  {
    id: 'showyourwork',
    title: 'Mostre Seu Trabalho',
    subtitle: null,
    author: 'Austin Kleon',
    year: 2014,
    pages: 224,
    color: '#f4a261',
    accent: '#264653',
    spine: 'warm',
    addedDays: 22,
    chapters: 10,
    highlights: 35,
    tags: ['criatividade'],
    status: 'processed',
  },
  {
    id: 'mans-search',
    title: 'Em Busca de Sentido',
    subtitle: null,
    author: 'Viktor Frankl',
    year: 1946,
    pages: 192,
    color: '#3d2817',
    accent: '#bfa181',
    spine: 'dark',
    addedDays: 401,
    chapters: 9,
    highlights: 58,
    tags: ['psicologia', 'filosofia'],
    status: 'processed',
  },
  {
    id: 'beginning-infinity',
    title: 'O Início do Infinito',
    subtitle: 'Explicações que transformam o mundo',
    author: 'David Deutsch',
    year: 2011,
    pages: 487,
    color: '#0d1b2a',
    accent: '#778da9',
    spine: 'cool',
    addedDays: 156,
    chapters: 18,
    highlights: 91,
    tags: ['filosofia', 'ciência'],
    status: 'processed',
  },
  {
    id: 'creativity-inc',
    title: 'Criatividade S.A.',
    subtitle: null,
    author: 'Ed Catmull',
    year: 2014,
    pages: 368,
    color: '#7d2e2e',
    accent: '#e8c39e',
    spine: 'warm',
    addedDays: 78,
    chapters: 15,
    highlights: 52,
    tags: ['criatividade', 'liderança'],
    status: 'processed',
  },
];

// Citations used by the chat answer
const CITATIONS_FLOW = [
  {
    n: 1,
    bookId: 'flow',
    chapter: 'Cap. 4 — As Condições do Flow',
    page: 87,
    quote: 'Os melhores momentos de nossas vidas não são os momentos passivos, receptivos, relaxados. Os melhores momentos geralmente ocorrem quando o corpo ou a mente de uma pessoa está sendo levado aos seus limites num esforço voluntário para realizar algo difícil e que valha a pena.',
  },
  {
    n: 2,
    bookId: 'deepwork',
    chapter: 'Cap. 1 — O Foco Profundo é Valioso',
    page: 34,
    quote: 'O esforço cognitivo intenso, sustentado e sem distrações é o que cria valor real no mundo do conhecimento. Tudo o que fica abaixo desse limiar — e-mails, reuniões, conversas paralelas — é trabalho raso que mal mantém o status quo.',
  },
  {
    n: 3,
    bookId: 'atomic',
    chapter: 'Cap. 12 — A Regra de Goldilocks',
    page: 218,
    quote: 'A motivação humana atinge o pico quando estamos trabalhando em desafios que ficam logo na borda das nossas capacidades atuais — não fáceis demais, não difíceis demais. Apenas certinho.',
  },
  {
    n: 4,
    bookId: 'thinking',
    chapter: 'Cap. 3 — O Controlador Preguiçoso',
    page: 71,
    quote: 'Quando estamos engajados ativamente em pensamento difícil, deixamos de ver o que normalmente veríamos. Os autores chamam esse fenômeno de "cegueira por desatenção".',
  },
  {
    n: 5,
    bookId: 'meditations',
    chapter: 'Livro VIII, §7',
    page: 142,
    quote: 'Toda natureza está contente consigo mesma quando segue seu próprio caminho; e a natureza racional segue seu próprio caminho quando, em seus pensamentos, não dá assentimento a nada falso ou incerto.',
  },
];

const SUGGESTED_QUESTIONS = [
  'Como diferentes autores definem disciplina?',
  'O que Taleb e Kahneman discordam sobre risco?',
  'Que livros do meu acervo falam sobre hábitos?',
  'Resuma a tese central de Sapiens em 3 parágrafos',
  'Conexões inesperadas entre Flow e estoicismo',
];

const HISTORY = [
  { id: 'h1', title: 'Como conciliar disciplina e criatividade?', daysAgo: 0, books: ['atomic', 'creativity-inc', 'showyourwork'] },
  { id: 'h2', title: 'O que é viver bem segundo os estoicos?', daysAgo: 1, books: ['meditations', 'mans-search'] },
  { id: 'h3', title: 'Sistema 1 vs Sistema 2 aplicado ao dia-a-dia', daysAgo: 3, books: ['thinking'] },
  { id: 'h4', title: 'Como Sapiens explica cooperação em larga escala', daysAgo: 5, books: ['sapiens'] },
  { id: 'h5', title: 'Antifragilidade no contexto pessoal', daysAgo: 8, books: ['antifragile', 'meditations'] },
  { id: 'h6', title: 'Hábitos pequenos têm impacto real?', daysAgo: 12, books: ['atomic', 'flow'] },
  { id: 'h7', title: 'Diferença entre conhecimento e sabedoria', daysAgo: 18, books: ['tao', 'meditations', 'beginning-infinity'] },
  { id: 'h8', title: 'Como David Deutsch define explicação?', daysAgo: 24, books: ['beginning-infinity'] },
];

const FLASHCARDS = [
  {
    front: 'Quais são as 3 condições essenciais para entrar em flow, segundo Csikszentmihalyi?',
    back: 'Objetivo claro, feedback imediato, e equilíbrio entre desafio e habilidade. Quando esses três se alinham, a atenção converge naturalmente e a auto-consciência desaparece.',
    bookId: 'flow',
    page: 87,
  },
  {
    front: 'O que diferencia "trabalho profundo" de "trabalho raso" para Cal Newport?',
    back: 'Trabalho profundo exige foco cognitivo intenso e sem distração — cria valor novo. Trabalho raso é logística: e-mails, reuniões, tarefas que mal mantêm o status quo.',
    bookId: 'deepwork',
    page: 34,
  },
  {
    front: 'Por que Taleb chama um sistema de "antifrágil" em vez de apenas "resiliente"?',
    back: 'Resiliente resiste a choques mantendo-se igual. Antifrágil ganha com choques — fica mais forte, melhor, mais inteligente quando exposto a volatilidade dentro de certos limites.',
    bookId: 'antifragile',
    page: 17,
  },
  {
    front: 'Qual a regra de Goldilocks aplicada a hábitos?',
    back: 'A motivação é máxima quando trabalhamos no limite da nossa capacidade — nem fácil demais (tédio), nem difícil demais (ansiedade). Apenas certinho.',
    bookId: 'atomic',
    page: 218,
  },
  {
    front: 'Segundo Marco Aurélio, qual é o "caminho" da natureza racional?',
    back: 'Não dar assentimento a nada falso ou incerto. A razão prospera quando se recusa a aceitar como verdadeiro aquilo que ainda não foi examinado.',
    bookId: 'meditations',
    page: 142,
  },
];

window.BOOKS = BOOKS;
window.CITATIONS_FLOW = CITATIONS_FLOW;
window.SUGGESTED_QUESTIONS = SUGGESTED_QUESTIONS;
window.HISTORY = HISTORY;
window.FLASHCARDS = FLASHCARDS;
window.bookById = (id) => BOOKS.find((b) => b.id === id);
